<a href="https://colab.research.google.com/github/ishraque675/test_demo/blob/master/Ishraque_day_4_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy


In [ ]:
#importing numpy

import numpy as np
#making list


lst=[1,2,3,4,5]
arr=np.array(lst)
print(repr(arr))

#making python matrix
matrix3=[[1,2,3],[4,5,6],[7,8,9]]
print(repr(np.array(matrix3)))





In [ ]:
#using builtin function
mat_arr=np.arange(1,18,2).reshape(3,3)

print(repr(mat_arr))

#random array
arr=np.random.randn(3,3)
print(arr)

#2d array
arr1=np.arange(1,6).reshape(5,1)
print(repr(arr1))

#shape
print(arr1.shape)

#accessing
ar1=np.arange(10)
print(ar1)
print(ar1[2]) #3rd element
print(ar1[3]) #4th element
print(ar1[8]) #9th element
print(ar1[0::2])




In [ ]:
#broadcasting
ar2=np.arange(10)
print(repr(ar2))
ar2[-3:]=100
print(repr(ar2))

In [75]:
#5X5 matrix
ar3=np.arange(1,51,2).reshape(5,5)
print(repr(ar3))

print(ar3[1:4,1:4])

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])
[[13 15 17]
 [23 25 27]
 [33 35 37]]
